### ISSUE TITLE
bufferutil as a devDependency breaks browserify builds

### ISSUE THREAD

**Issue by jkamke** [websockets/ws#649]
This worked with ws@0.8.1 when bufferutil was an optionalDependency.

Simply try: 

```shell
browserify test.js 
Error: Cannot find module 'bufferutil' from ...
```

where test.js:
```javascript
var ws = require('ws');
```

**Comment by 3rd-Eden** [comment]
No, it doesn't work because I removed the client code. See release notes.

**Comment by kirillkostko** [comment]
+1
I have the same issue.
